version: 2.1

jobs:              
  test-frontend:
    docker: 
      - image: python:3.7.3-stretch
    steps:
      - checkout # checkout source code from git
      - run:
          name: Install dependencies
          command: |
            cd HelloWorld
            make install
      - run:
          name: check lint
          command: |
            cd HelloWorld
            make lint
                       
workflows:
  default:
    jobs:
      - test-frontend