apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: helloworld-cluster
  region: us-east-1
  zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.small
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        imageBuilder: true